# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20161007_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='moth_cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processor',
            name='proc_cost',
            field=models.IntegerField(default=123412),
            preserve_default=False,
        ),
    ]
