# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20161007_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_model', models.CharField(max_length=100)),
                ('case_socket', models.IntegerField()),
                ('case_watts', models.IntegerField()),
                ('case_content', models.TextField()),
                ('case_cost', models.IntegerField()),
                ('case_image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPU_model', models.CharField(max_length=100)),
                ('GPU_socket', models.IntegerField()),
                ('GPU_watts', models.IntegerField()),
                ('GPU_content', models.TextField()),
                ('GPU_cost', models.IntegerField()),
                ('GPU_image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_model', models.CharField(max_length=100)),
                ('mem_socket', models.IntegerField()),
                ('mem_watts', models.IntegerField()),
                ('mem_content', models.TextField()),
                ('mem_cost', models.IntegerField()),
                ('mem_image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSU_model', models.CharField(max_length=100)),
                ('PSU_socket', models.IntegerField()),
                ('PSU_watts', models.IntegerField()),
                ('PSU_content', models.TextField()),
                ('PSU_cost', models.IntegerField()),
                ('PSU_image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_model', models.CharField(max_length=100)),
                ('store_socket', models.IntegerField()),
                ('store_watts', models.IntegerField()),
                ('store_content', models.TextField()),
                ('store_cost', models.IntegerField()),
                ('store_image', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
