# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_case_gpu_memory_psu_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='moth_content',
            new_name='mobo_content',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='moth_cost',
            new_name='mobo_cost',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='moth_image',
            new_name='mobo_image',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='moth_model',
            new_name='mobo_model',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='moth_socket',
            new_name='mobo_socket',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='moth_watts',
            new_name='mobo_watts',
        ),
        migrations.AlterField(
            model_name='processor',
            name='proc_image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
