# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20161010_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_socket',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_watts',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='GPU_socket',
        ),
        migrations.RemoveField(
            model_name='psu',
            name='PSU_socket',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='store_socket',
        ),
    ]
