# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_processor_proc_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='GPU_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memory',
            name='mem_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='mobo_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='psu',
            name='PSU_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='store_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processor',
            name='proc_qty',
            field=models.IntegerField(default=0),
        ),
    ]
