# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='last_updated',
        ),
    ]
