# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20161015_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Processor')),
            ],
        ),
    ]
