# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_order_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=111),
            preserve_default=False,
        ),
    ]
